name: Nicks Site
markdown: redcarpet
highlighter: pygments
permalink: none

prose:
  rooturl: '_posts'
  siteurl: 'http://nickphillipps.co.uk/'
  media: 'img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes